
SUBDIR = apply basename cal cmp col colrm column comm csplit cut \
	 diff diff3 dirname du env expand false find fold head \
	 hexdump id join mkdep mktemp nice nl nohup paste patch \
	 printenv printf readlink realpath sort split stat tail \
	 tee touch tr tsort tty uname unexpand uniq wc what which \
	 xargs xinstall yes

.include <bsd.subdir.mk>
