
SUBDIR = apply basename cal cmp col colrm column comm csplit cut \
	 diff diff3 dirname du env expand false find fold head \
	 hexdump id join lex md5 mkdep mktemp nice nl nohup paste patch \
	 printenv printf readlink realpath sort split stat tail \
	 tee touch tsort tr true tty uname unexpand uniq wc what which \
	 xargs xinstall yes

.include <bsd.subdir.mk>
