
LIB = openbsd

COPTS += -Ihidden -Iinclude -I../include

.include "compat/Makefile.inc"
.include "crypt/Makefile.inc"
.include "db/Makefile.inc"
.include "gen/Makefile.inc"
.include "hash/Makefile.inc"
.include "stdio/Makefile.inc"
.include "stdlib/Makefile.inc"
.include "string/Makefile.inc"
.include "util/Makefile.inc"

.include "../mk.config"
.include <bsd.lib.mk>
